### ISSUE TITLE
Dungeons are checked regardless of whether they are accessible to the player

### ISSUE THREAD

**Issue by mpolewaczyk** [gar-r/lfgmon#1]
Currently function `checker:GetShortages()` check for all dungeson/raids regardless of whether they are accessible to the player. It should be limited to available only.

There is a function `IsLFGDungeonJoinable(dungeonId)` which allows to check only valid dungeons/raids

**Comment by gar-r** [comment]
Added article:
https://warcraft.wiki.gg/wiki/API_IsLFGDungeonJoinablehttps://warcraft.wiki.gg/wiki/API_IsLFGDungeonJoinable
